#!/usr/bin/env node
// Regenerates glyphs.js: every non-ASCII character used by the scenes, so the web fonts
// (split into unicode-range slices by Google Fonts) are fully loaded before the first frame.
const fs = require('fs'), path = require('path');
const dir = __dirname, set = new Set();
for (const f of fs.readdirSync(dir)) {
  if (!/\.js$/.test(f) || f === 'glyphs.js') continue;
  for (const ch of fs.readFileSync(path.join(dir, f), 'utf8')) if (ch.codePointAt(0) > 0x7e) set.add(ch);
}
const s = [...set].sort().join('');
fs.writeFileSync(path.join(dir, 'glyphs.js'), `// generated by glyphs.cjs — characters drawn by the scenes\nwindow.GLYPHS = ${JSON.stringify(s)};\n`);
console.log(`glyphs.js: ${set.size} characters`);
